server:
  port: 8080

spring:
  application:
    name: GeneratorDemo

  #数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/generator_demo?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: root

logging:
  level:
    #控制台打印mapper接口的sql语句日志
    com.rawchen.generatordemo.mapper: debug